In [3]:
from ultralytics import YOLO

# Load a model
model = YOLO('runs/detect/train4/weights/best.pt')  # pretrained YOLOv8n model

# Run batched inference on a list of images
results = model([r'C:/Users/RND/Downloads/GABUNGAN/Screenshot 2024-01-05 102227.png'])  # return a list of Results objects

# Process results list
for result in results:
    boxes = result.boxes  # Boxes object for bbox outputs
# Konversi tensor PyTorch ke NumPy array
numpy_array = boxes.xywhn.cpu().numpy()

# Konversi tensor PyTorch ke NumPy array
numpy_arraycls = boxes.cls.cpu().numpy()


for cls, [x, y, w, h] in zip(numpy_arraycls, numpy_array):
    hasil =f"{int(cls)}, {x}, {y}, {w}, {h}"



0: 544x640 1 3, 1 4, 1 7, 1 B, 1 E, 1 J, 1 V, 28.0ms
Speed: 4.9ms preprocess, 28.0ms inference, 2.0ms postprocess per image at shape (1, 3, 544, 640)
[[    0.84317     0.73215    0.083186     0.16485]
 [    0.75736     0.70982    0.070456     0.17229]
 [    0.10402     0.54958    0.072094     0.16447]
 [    0.67319     0.68904    0.084339     0.16021]
 [     0.4285     0.62677    0.072704     0.15624]
 [    0.52515     0.65025    0.080774     0.14811]
 [    0.34789     0.60894    0.074071     0.16402]]
[         19          31          11          14           7           4           3]
19, 0.8431662321090698, 0.7321462631225586, 0.08318617194890976, 0.16484566032886505
31, 0.7573609948158264, 0.7098151445388794, 0.07045630365610123, 0.1722933053970337
11, 0.10401546210050583, 0.5495774149894714, 0.07209432125091553, 0.1644735038280487
14, 0.6731868386268616, 0.6890446543693542, 0.08433939516544342, 0.16021433472633362
7, 0.4284988343715668, 0.6267668604850769, 0.07270412892103195, 0.

In [4]:
from ultralytics import YOLO
import os

# Load a model
model = YOLO('runs/detect/train4/weights/best.pt')  # pretrained YOLOv8n model

# Image path
image_path = r'C:/Users/RND/Downloads/GABUNGAN/Screenshot 2024-01-05 102227.png'

# Run batched inference on a list of images
results = model([image_path])  # return a list of Results objects

# Process results list
for result in results:
    boxes = result.boxes  # Boxes object for bbox outputs

# Konversi tensor PyTorch ke NumPy array
numpy_array = boxes.xywhn.cpu().numpy()

# Konversi tensor PyTorch ke NumPy array
numpy_arraycls = boxes.cls.cpu().numpy()

# Mendapatkan nama file tanpa ekstensi dan menggabungkannya dengan ekstensi .txt
base_filename = os.path.splitext(os.path.basename(image_path))[0]
txt_filename = f'{base_filename}.txt'

# Membuka file untuk menulis (mode 'w' berarti write)
with open(txt_filename, 'w') as file:
    # Iterasi melalui hasil dan menulis ke dalam file
    for cls, [x, y, w, h] in zip(numpy_arraycls, numpy_array):
        hasil = f"{int(cls)}, {x}, {y}, {w}, {h}"
        file.write(hasil + '\n')  # Menambahkan newline untuk setiap baris

# File akan ditutup secara otomatis setelah blok with selesai



0: 544x640 1 3, 1 4, 1 7, 1 B, 1 E, 1 J, 1 V, 39.0ms
Speed: 5.0ms preprocess, 39.0ms inference, 3.0ms postprocess per image at shape (1, 3, 544, 640)


In [8]:
from ultralytics import YOLO
import os

# Load a model
model = YOLO('runs/detect/train4/weights/best.pt')  # pretrained YOLOv8n model

# Image path
image_path = r'C:/Users/RND/Downloads/GABUNGAN/Screenshot 2024-01-05 102227.png'

# Run batched inference on a list of images
results = model([image_path])  # return a list of Results objects

# Process results list
for result in results:
    boxes = result.boxes  # Boxes object for bbox outputs

# Konversi tensor PyTorch ke NumPy array
numpy_array = boxes.xywhn.cpu().numpy()

# Konversi tensor PyTorch ke NumPy array
numpy_arraycls = boxes.cls.cpu().numpy()

# Mendapatkan nama file tanpa ekstensi dan menggabungkannya dengan ekstensi .txt
base_filename = os.path.splitext(os.path.basename(image_path))[0]
txt_filename = f'{base_filename}.txt'

# Membuka file untuk menulis (mode 'w' berarti write)
with open(txt_filename, 'w') as file:
    # Iterasi melalui hasil dan menulis ke dalam file
    for cls, [x, y, w, h] in zip(numpy_arraycls, numpy_array):
        hasil = f"{int(cls)}, {x}, {y}, {w}, {h}"
        file.write(hasil + '\n')  # Menambahkan newline untuk setiap baris
# Mendapatkan nama file tanpa ekstensi dan menggabungkannya dengan ekstensi .txt
base_filename = os.path.splitext(os.path.basename(image_path))[0]
txt_filename = f'{base_filename}.txt'

# Membaca isi file
with open(txt_filename, 'r') as file:
    lines = file.readlines()

# Memodifikasi setiap baris dan mengganti koma dengan spasi
modified_lines = [line.replace(',','') for line in lines]

# Menulis kembali hasil yang sudah dimodifikasi ke dalam file
with open(txt_filename, 'w') as file:
    file.writelines(modified_lines)



0: 544x640 1 3, 1 4, 1 7, 1 B, 1 E, 1 J, 1 V, 27.0ms
Speed: 4.2ms preprocess, 27.0ms inference, 2.0ms postprocess per image at shape (1, 3, 544, 640)


DALAM BENTUK FOLDER

In [15]:
import os
import glob
from ultralytics import YOLO

# Path ke folder yang berisi file gambar
folder_path = r'C:\Users\RND\Downloads\GABUNGAN\train\images'

# Mendapatkan semua file dengan ekstensi .png dalam folder
image_files = glob.glob(os.path.join(folder_path, '*.jpg'))

# Membuat folder untuk menyimpan file txt
output_folder = os.path.join(folder_path, 'label_txt')
os.makedirs(output_folder, exist_ok=True)

# Iterasi melalui setiap file dalam folder
for image_path in image_files:
    # Load a model
    model = YOLO('runs/detect/train4/weights/best.pt')  # pretrained YOLOv8n model

    # Run batched inference on a list of images
    results = model([image_path])  # return a list of Results objects

    # Process results list
    for result in results:
        boxes = result.boxes  # Boxes object for bbox outputs

    # Konversi tensor PyTorch ke NumPy array
    numpy_array = boxes.xywhn.cpu().numpy()

    # Konversi tensor PyTorch ke NumPy array
    numpy_arraycls = boxes.cls.cpu().numpy()

    # Mendapatkan nama file tanpa ekstensi dan menggabungkannya dengan ekstensi .txt
    base_filename = os.path.splitext(os.path.basename(image_path))[0]
    txt_filename = f'{base_filename}.txt'

    # Path lengkap ke file txt
    txt_filepath = os.path.join(output_folder, txt_filename)

    # Membuka file untuk menulis (mode 'w' berarti write)
    with open(txt_filepath, 'w') as file:
        # Iterasi melalui hasil dan menulis ke dalam file
        for cls, [x, y, w, h] in zip(numpy_arraycls, numpy_array):
            hasil = f"{int(cls)} {x} {y} {w} {h}"
            sorted_boxes = sorted(hasil, key=lambda box: box[0])
            file.write(hasil + '\n')  # Menambahkan newline untuk setiap baris



0: 288x640 1 0, 1 1, 1 2, 1 5, 1 B, 1 U, 1 W, 17.0ms
Speed: 3.1ms preprocess, 17.0ms inference, 4.0ms postprocess per image at shape (1, 3, 288, 640)

0: 512x640 1 2, 2 4s, 1 7, 1 9, 1 A, 1 B, 1 F, 1 K, 13.1ms
Speed: 0.9ms preprocess, 13.1ms inference, 2.1ms postprocess per image at shape (1, 3, 512, 640)

0: 288x640 1 1, 1 2, 2 6s, 1 B, 1 D, 1 F, 1 T, 6.9ms
Speed: 1.0ms preprocess, 6.9ms inference, 5.0ms postprocess per image at shape (1, 3, 288, 640)

0: 288x640 1 1, 2 5s, 1 6, 1 B, 1 H, 1 N, 1 S, 1 Z, 14.0ms
Speed: 0.0ms preprocess, 14.0ms inference, 1.1ms postprocess per image at shape (1, 3, 288, 640)

0: 288x640 1 1, 1 2, 2 6s, 2 Bs, 1 F, 1 T, 15.5ms
Speed: 2.0ms preprocess, 15.5ms inference, 3.0ms postprocess per image at shape (1, 3, 288, 640)

0: 288x640 1 1, 1 2, 1 6, 1 8, 2 Bs, 1 F, 1 O, 1 T, 14.5ms
Speed: 1.0ms preprocess, 14.5ms inference, 3.0ms postprocess per image at shape (1, 3, 288, 640)

0: 320x640 1 1, 2 5s, 1 6, 1 B, 1 H, 1 N, 1 S, 1 Z, 16.7ms
Speed: 1.0ms preproc

PEMBAHARUAN KODE UNTUK MENGURUTKAN BERDASARKAN KOORDINAT X

In [2]:
import os
import glob
import numpy as np
from ultralytics import YOLO

# Path ke folder yang berisi file gambar
folder_path = r'C:\Users\RND\Downloads\GABUNGAN\train\images'

# Mendapatkan semua file dengan ekstensi .jpg dalam folder
image_files = glob.glob(os.path.join(folder_path, '*.jpg'))

# Membuat folder untuk menyimpan file txt
output_folder = os.path.join(folder_path, 'label_txtbaru')
os.makedirs(output_folder, exist_ok=True)

# Iterasi melalui setiap file dalam folder
for image_path in image_files:
    # Load a model
    model = YOLO('runs/detect/train4/weights/best.pt')  # pretrained YOLOv8n model

    # Run batched inference on a list of images
    results = model([image_path])  # return a list of Results objects

    # Process results list
    for result in results:
        boxes = result.boxes  # Boxes object for bbox outputs

    # Konversi tensor PyTorch ke NumPy array
    numpy_array = boxes.xywhn.cpu().numpy()

    # Konversi tensor PyTorch ke NumPy array
    numpy_arraycls = boxes.cls.cpu().numpy()

    # Mendapatkan nama file tanpa ekstensi dan menggabungkannya dengan ekstensi .txt
    base_filename = os.path.splitext(os.path.basename(image_path))[0]
    txt_filename = f'{base_filename}.txt'

    # Path lengkap ke file txt
    txt_filepath = os.path.join(output_folder, txt_filename)

    # Membuka file untuk menulis (mode 'w' berarti write)
    with open(txt_filepath, 'w') as file:
        # Gabungkan data menjadi satu array NumPy
        data = np.column_stack((numpy_arraycls, numpy_array))

        # Urutkan data berdasarkan kolom pertama (x)
        sorted_data = data[data[:, 1].argsort()]

        # Iterasi melalui hasil yang sudah diurutkan dan menulis ke dalam file
        for row in sorted_data:
            cls = int(row[0])
            x, y, w, h = row[1:]
            line = f"{cls} {x} {y} {w} {h}"
            file.write(line + '\n')  # Menambahkan newline untuk setiap baris



0: 288x640 1 0, 1 1, 1 2, 1 5, 1 B, 1 U, 1 W, 21.1ms
Speed: 3.0ms preprocess, 21.1ms inference, 6.9ms postprocess per image at shape (1, 3, 288, 640)

0: 512x640 1 2, 2 4s, 1 7, 1 9, 1 A, 1 B, 1 F, 1 K, 127.4ms
Speed: 2.9ms preprocess, 127.4ms inference, 4.0ms postprocess per image at shape (1, 3, 512, 640)

0: 288x640 1 1, 1 2, 2 6s, 1 B, 1 D, 1 F, 1 T, 17.0ms
Speed: 2.0ms preprocess, 17.0ms inference, 2.0ms postprocess per image at shape (1, 3, 288, 640)

0: 288x640 1 1, 2 5s, 1 6, 1 B, 1 H, 1 N, 1 S, 1 Z, 15.0ms
Speed: 1.0ms preprocess, 15.0ms inference, 2.0ms postprocess per image at shape (1, 3, 288, 640)

0: 288x640 1 1, 1 2, 2 6s, 2 Bs, 1 F, 1 T, 18.9ms
Speed: 2.0ms preprocess, 18.9ms inference, 2.0ms postprocess per image at shape (1, 3, 288, 640)

0: 288x640 1 1, 1 2, 1 6, 1 8, 2 Bs, 1 F, 1 O, 1 T, 13.0ms
Speed: 1.0ms preprocess, 13.0ms inference, 2.0ms postprocess per image at shape (1, 3, 288, 640)

0: 320x640 1 1, 2 5s, 1 6, 1 B, 1 H, 1 N, 1 S, 1 Z, 98.5ms
Speed: 2.0ms pre

In [6]:
import os
import glob
import numpy as np
from ultralytics import YOLO

# Path ke folder yang berisi file gambar
folder_path = r'C:\Users\RND\Downloads\GABUNGAN\train\images'

# Mendapatkan semua file dengan ekstensi .jpg dalam folder
image_files = glob.glob(os.path.join(folder_path, '*.jpg'))

# Membuat folder untuk menyimpan file txt
output_folder = os.path.join(folder_path, 'label_txtbaru')
os.makedirs(output_folder, exist_ok=True)

# Iterasi melalui setiap file dalam folder
for image_path in image_files:
    # Load a model
    model = YOLO('runs/detect/train4/weights/best.pt')  # pretrained YOLOv8n model

    # Run batched inference on a list of images
    results = model([image_path])  # return a list of Results objects

    # Process results list
    for result in results:
        boxes = result.boxes  # Boxes object for bbox outputs

    # Konversi tensor PyTorch ke NumPy array
    numpy_array = boxes.xywhn.cpu().numpy()
    print(boxes.cls)
    print(numpy_array)
    print(result.boxes)
    
    break


0: 288x640 1 0, 1 1, 1 2, 1 5, 1 B, 1 U, 1 W, 21.0ms
Speed: 2.6ms preprocess, 21.0ms inference, 2.0ms postprocess per image at shape (1, 3, 288, 640)
tensor([ 0.,  2.,  5., 30., 11., 32.,  1.], device='cuda:0')
[[    0.48493     0.42911    0.077164     0.40435]
 [    0.56504     0.46363    0.084845     0.39897]
 [    0.40735     0.39513    0.080369     0.41861]
 [     0.7665     0.54078    0.077111      0.4025]
 [    0.18379     0.31661    0.087786     0.39125]
 [    0.68629     0.51957     0.08318     0.37757]
 [    0.32899     0.37023    0.080725     0.40533]]
ultralytics.engine.results.Boxes object with attributes:

cls: tensor([ 0.,  2.,  5., 30., 11., 32.,  1.], device='cuda:0')
conf: tensor([0.9378, 0.9337, 0.9317, 0.8992, 0.8461, 0.7186, 0.7002], device='cuda:0')
data: tensor([[37.4933,  7.9429, 43.9750, 22.0950,  0.9378,  0.0000],
        [43.9002,  9.2449, 51.0272, 23.2090,  0.9337,  2.0000],
        [30.8421,  6.5036, 37.5930, 21.1551,  0.9317,  5.0000],
        [61.1469, 11

In [4]:
boxes.xywhn

tensor([[0.8432, 0.7321, 0.0832, 0.1648],
        [0.7574, 0.7098, 0.0705, 0.1723],
        [0.1040, 0.5496, 0.0721, 0.1645],
        [0.6732, 0.6890, 0.0843, 0.1602],
        [0.4285, 0.6268, 0.0727, 0.1562],
        [0.5251, 0.6502, 0.0808, 0.1481],
        [0.3479, 0.6089, 0.0741, 0.1640]], device='cuda:0')

In [17]:
from ultralytics import YOLO
import os

# Load a model
model = YOLO('runs/detect/train4/weights/best.pt')  # pretrained YOLOv8n model

# Image path
image_path = r'C:/Users/RND/Downloads/GABUNGAN/Screenshot 2024-01-05 102227.png'

# Run batched inference on a list of images
results = model([image_path])  # return a list of Results objects

# Process results list
for result in results:
    boxes = result.boxes  # Boxes object for bbox outputs

# Konversi tensor PyTorch ke NumPy array
numpy_array = boxes.xywhn.cpu().numpy()

# Konversi tensor PyTorch ke NumPy array
numpy_arraycls = boxes.cls.cpu().numpy()

# Iterasi melalui hasil dan menulis ke dalam file
# List kosong untuk menyimpan semua list hasil
all_results = []

# Iterasi melalui hasil dan menulis ke dalam file
for cls, [x, y, w, h] in zip(numpy_arraycls, numpy_array):
    hasil = f"{int(cls)},{x},{y},{w},{h}"
    
    # Memisahkan string menjadi list menggunakan koma sebagai delimiter
    list_data = hasil.split(',')
    
    # Mengubah elemen-elemen ke tipe float
    float_list_data = [float(item) for item in list_data]
    
    # Menampilkan list yang dihasilkan
    print(float_list_data)
    
    # Menambahkan list hasil ke dalam list utama
    all_results.append(float_list_data)

# Menampilkan list yang berisi semua list hasil
print(all_results)


    # file.write(hasil + '\n')  # Menambahkan newline untuk setiap baris
# # Mendapatkan nama file tanpa ekstensi dan menggabungkannya dengan ekstensi .txt
# base_filename = os.path.splitext(os.path.basename(image_path))[0]
# txt_filename = f'{base_filename}.txt'

# # Membaca isi file
# with open(txt_filename, 'r') as file:
#     lines = file.readlines()

# # Memodifikasi setiap baris dan mengganti koma dengan spasi
# modified_lines = [line.replace(',','') for line in lines]

# # Menulis kembali hasil yang sudah dimodifikasi ke dalam file
# with open(txt_filename, 'w') as file:
#     file.writelines(modified_lines)



0: 544x640 1 3, 1 4, 1 7, 1 B, 1 E, 1 J, 1 V, 26.6ms
Speed: 4.0ms preprocess, 26.6ms inference, 2.0ms postprocess per image at shape (1, 3, 544, 640)
[19.0, 0.8431662321090698, 0.7321462631225586, 0.08318617194890976, 0.16484566032886505]
[31.0, 0.7573609948158264, 0.7098151445388794, 0.07045630365610123, 0.1722933053970337]
[11.0, 0.10401546210050583, 0.5495774149894714, 0.07209432125091553, 0.1644735038280487]
[14.0, 0.6731868386268616, 0.6890446543693542, 0.08433939516544342, 0.16021433472633362]
[7.0, 0.4284988343715668, 0.6267668604850769, 0.07270412892103195, 0.1562356948852539]
[4.0, 0.5251450538635254, 0.650249719619751, 0.0807737186551094, 0.1481102854013443]
[3.0, 0.3478851020336151, 0.608938455581665, 0.07407143712043762, 0.16402417421340942]
[[19.0, 0.8431662321090698, 0.7321462631225586, 0.08318617194890976, 0.16484566032886505], [31.0, 0.7573609948158264, 0.7098151445388794, 0.07045630365610123, 0.1722933053970337], [11.0, 0.10401546210050583, 0.5495774149894714, 0.07209

In [19]:
# List kosong untuk menyimpan semua list hasil
all_results = []

# Iterasi melalui hasil dan menulis ke dalam file
for index, (cls, [x, y, w, h]) in enumerate(zip(numpy_arraycls, numpy_array)):
    hasil = f"{int(cls)},{x},{y},{w},{h}"
    
    # Memisahkan string menjadi list menggunakan koma sebagai delimiter
    list_data = hasil.split(',')
    
    # Mengubah elemen-elemen ke tipe float
    float_list_data = [float(item) for item in list_data]
    
    # Menampilkan list yang dihasilkan
    print(float_list_data)
    
    # Menambahkan list hasil ke dalam list utama
    all_results.append(float_list_data)

    # Menampilkan indeks saat ini
    print(f'Index: {index}')

# Menampilkan list yang berisi semua list hasil
print(all_results)


[19.0, 0.8431662321090698, 0.7321462631225586, 0.08318617194890976, 0.16484566032886505]
Index: 0
[31.0, 0.7573609948158264, 0.7098151445388794, 0.07045630365610123, 0.1722933053970337]
Index: 1
[11.0, 0.10401546210050583, 0.5495774149894714, 0.07209432125091553, 0.1644735038280487]
Index: 2
[14.0, 0.6731868386268616, 0.6890446543693542, 0.08433939516544342, 0.16021433472633362]
Index: 3
[7.0, 0.4284988343715668, 0.6267668604850769, 0.07270412892103195, 0.1562356948852539]
Index: 4
[4.0, 0.5251450538635254, 0.650249719619751, 0.0807737186551094, 0.1481102854013443]
Index: 5
[3.0, 0.3478851020336151, 0.608938455581665, 0.07407143712043762, 0.16402417421340942]
Index: 6
[[19.0, 0.8431662321090698, 0.7321462631225586, 0.08318617194890976, 0.16484566032886505], [31.0, 0.7573609948158264, 0.7098151445388794, 0.07045630365610123, 0.1722933053970337], [11.0, 0.10401546210050583, 0.5495774149894714, 0.07209432125091553, 0.1644735038280487], [14.0, 0.6731868386268616, 0.6890446543693542, 0.0843

In [5]:
# Konversi tensor PyTorch ke NumPy array
numpy_array = boxes.xywhn.cpu().numpy()

# Tampilkan array
print(numpy_array)

[[    0.84317     0.73215    0.083186     0.16485]
 [    0.75736     0.70982    0.070456     0.17229]
 [    0.10402     0.54958    0.072094     0.16447]
 [    0.67319     0.68904    0.084339     0.16021]
 [     0.4285     0.62677    0.072704     0.15624]
 [    0.52515     0.65025    0.080774     0.14811]
 [    0.34789     0.60894    0.074071     0.16402]]


In [6]:
numpy_array[0]

array([    0.84317,     0.73215,    0.083186,     0.16485], dtype=float32)

In [7]:
print(boxes)

ultralytics.engine.results.Boxes object with attributes:

cls: tensor([19., 31., 11., 14.,  7.,  4.,  3.], device='cuda:0')
conf: tensor([0.8191, 0.7720, 0.7187, 0.6859, 0.4971, 0.3933, 0.3678], device='cuda:0')
data: tensor([[7.5188e+02, 5.1003e+02, 8.2990e+02, 6.3944e+02, 8.1909e-01, 1.9000e+01],
        [6.7736e+02, 4.8958e+02, 7.4345e+02, 6.2483e+02, 7.7201e-01, 3.1000e+01],
        [6.3754e+01, 3.6686e+02, 1.3138e+02, 4.9597e+02, 7.1874e-01, 1.1000e+01],
        [5.9189e+02, 4.7802e+02, 6.7100e+02, 6.0378e+02, 6.8588e-01, 1.4000e+01],
        [3.6783e+02, 4.3069e+02, 4.3603e+02, 5.5333e+02, 4.9710e-01, 7.0000e+00],
        [4.5470e+02, 4.5231e+02, 5.3047e+02, 5.6858e+02, 3.9330e-01, 4.0000e+00],
        [2.9158e+02, 4.1364e+02, 3.6106e+02, 5.4240e+02, 3.6783e-01, 3.0000e+00]], device='cuda:0')
id: None
is_track: False
orig_shape: (785, 938)
shape: torch.Size([7, 6])
xywh: tensor([[790.8899, 574.7348,  78.0286, 129.4038],
        [710.4046, 557.2049,  66.0880, 135.2502],
        [ 

In [8]:
boxes.cls

tensor([19., 31., 11., 14.,  7.,  4.,  3.], device='cuda:0')

In [9]:
# Konversi tensor PyTorch ke NumPy array
numpy_arraycls = boxes.cls.cpu().numpy()

# Tampilkan array
print(numpy_arraycls)

[         19          31          11          14           7           4           3]


In [15]:
for cls, [x, y, w, h] in zip(numpy_arraycls, numpy_array):
    print( data_str = f"{int(cls)}, {x}, {y}, {w}, {h}")

19, 0.8431662321090698, 0.7321462631225586, 0.08318617194890976, 0.16484566032886505
31, 0.7573609948158264, 0.7098151445388794, 0.07045630365610123, 0.1722933053970337
11, 0.10401546210050583, 0.5495774149894714, 0.07209432125091553, 0.1644735038280487
14, 0.6731868386268616, 0.6890446543693542, 0.08433939516544342, 0.16021433472633362
7, 0.4284988343715668, 0.6267668604850769, 0.07270412892103195, 0.1562356948852539
4, 0.5251450538635254, 0.650249719619751, 0.0807737186551094, 0.1481102854013443
3, 0.3478851020336151, 0.608938455581665, 0.07407143712043762, 0.16402417421340942


In [20]:
all_results = []

# Iterasi melalui hasil dan menulis ke dalam file
for index, (cls, [x, y, w, h]) in enumerate(zip(numpy_arraycls, numpy_array)):
    hasil = f"{int(cls)},{x},{y},{w},{h}"
    
    # Memisahkan string menjadi list menggunakan koma sebagai delimiter
    list_data = hasil.split(',')
    
    # Mengubah elemen-elemen ke tipe float
    float_list_data = [float(item) for item in list_data]
    
    # Menampilkan list yang dihasilkan
    print(float_list_data)
    
    # Menambahkan list hasil ke dalam list utama
    all_results.append(float_list_data)

[19.0, 0.8431662321090698, 0.7321462631225586, 0.08318617194890976, 0.16484566032886505]
[31.0, 0.7573609948158264, 0.7098151445388794, 0.07045630365610123, 0.1722933053970337]
[11.0, 0.10401546210050583, 0.5495774149894714, 0.07209432125091553, 0.1644735038280487]
[14.0, 0.6731868386268616, 0.6890446543693542, 0.08433939516544342, 0.16021433472633362]
[7.0, 0.4284988343715668, 0.6267668604850769, 0.07270412892103195, 0.1562356948852539]
[4.0, 0.5251450538635254, 0.650249719619751, 0.0807737186551094, 0.1481102854013443]
[3.0, 0.3478851020336151, 0.608938455581665, 0.07407143712043762, 0.16402417421340942]


In [1]:
# Membuka file untuk menulis (mode 'w' berarti write)
with open('hasil.txt', 'w') as file:
    # Iterasi melalui kedua array secara bersamaan
    for cls, coords in zip(numpy_arraycls, numpy_array):
        # Membuat string hasil
        data_str = f"{int(cls)}, {', '.join(map(str, coords))}"

        # Menulis string ke dalam file
        file.write(data_str + '\n')

NameError: name 'numpy_arraycls' is not defined

In [17]:
import numpy as np

# Array dua dimensi (matriks)
array2 = np.array([
    [19, 0.8431662321090698, 0.7321462631225586, 0.08318617194890976, 0.16484566032886505],
    [31, 0.7573609948158264, 0.7098151445388794, 0.07045630365610123, 0.1722933053970337],
    [11, 0.10401546210050583, 0.5495774149894714, 0.07209432125091553, 0.1644735038280487],
    [14, 0.6731868386268616, 0.6890446543693542, 0.08433939516544342, 0.16021433472633362],
    [7, 0.4284988343715668, 0.6267668604850769, 0.07270412892103195, 0.1562356948852539],
    [4, 0.5251450538635254, 0.650249719619751, 0.0807737186551094, 0.1481102854013443],
    [3, 0.3478851020336151, 0.608938455581665, 0.07407143712043762, 0.16402417421340942]
])

print(array2) # XYWH

[[         19     0.84317     0.73215    0.083186     0.16485]
 [         31     0.75736     0.70982    0.070456     0.17229]
 [         11     0.10402     0.54958    0.072094     0.16447]
 [         14     0.67319     0.68904    0.084339     0.16021]
 [          7      0.4285     0.62677    0.072704     0.15624]
 [          4     0.52515     0.65025    0.080774     0.14811]
 [          3     0.34789     0.60894    0.074071     0.16402]]
